[package]
name = "ssh2-rs-bench"
version = "0.1.0"
authors = ["Sathiyan Sivathas <sathiyan.sivathas@metaswitch.com>"]
edition = "2018"
publish = ["metaswitch"]

[[bin]]
name = "ssh2"
path = "src/ssh2.rs"

[dependencies]
anyhow = "1"
ssh2 = "0.8"
